name: Laravel-deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action
        with:
          host: ${{ secrets.ABDELILAH_HOSTINGER_SSH_SERVER }}
          username: ${{ secrets.ABDELILAH_HOSTINGER_SSH_USERNAME }}
          password: ${{ secrets.ABDELILAH_HOSTINGER_SSH_PASSWORD }}
          port: ${{ secrets.ABDELILAH_HOSTINGER_SSH_PORT }}
          script: |
            cd domains/abezdev.com/public_html 
            git checkout -f
            git pull